#################################################################################
# Copyright (c) 2022,2024 T-Systems International GmbH
# Copyright (c) 2022,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

server:
  port: 8080
  error:
    include-message: always
keycloak:
  resource:
    clientid: Cl2-CX-Portal
spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: catena-x-ctx
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: https://centralidp.example.com/auth/realms/CX-Central/protocol/openid-connect/certs
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /SDFactoryApi-vRel3.yml
app:
  build:
    version: ^project.version^
  verifiableCredentials:
    durationDays: 90
    #schema2210Url: 
    gaia-x-participant-schema: https://registry.lab.gaia-x.eu/development/api/trusted-schemas-registry/v2/schemas
    gaia-x-service-schema: https://gaia-x.gitlab.io/gaia-x-community/gaia-x-self-descriptions/service/ontology.json
  usersDetails:
    clearingHouse:
      #uri: https://validation.example.com/api/v1/compliance
      #auth-server-url: https://iam.example.com//auth
      #realm: notarisation
      #clientId: CARLA-GXDCH
      #clientSecret:
  security:
    createRole: add_self_descriptions
logging:
  level:
    org.eclipse.tractusx.selfdescriptionfactory: DEBUG
management:
  health:
    defaults:
      enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
