openapi: 3.0.0
info:
  version: Release3
  title: SD-Factory API
  description: API for creating and storing the Verifiable Credentials
paths:
  /api/rel3/selfdescription:
    post:
      summary: Creates a Verifiable Credential and returns it
      operationId: selfdescriptionPost
      requestBody:
        required: true
        description: parameters to generate VC
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/LegalPersonSchema'
                - $ref: '#/components/schemas/ServiceOfferingSchema'
              discriminator:
                propertyName: type
                mapping:
                  LegalParticipant: '#/components/schemas/LegalPersonSchema'
                  ServiceOffering: '#/components/schemas/ServiceOfferingSchema'
            examples:
              LegalPerson:
                description: payload to create LegalPerson
                value:
                    externalId: ID01234-123-4321
                    type: LegalPerson
                    holder: BPNL000000000000
                    issuer: CAXSDUMMYCATENAZZ
                    registrationNumber:
                      - type: taxID
                        value: o12345678
                    headquarterAddress.country: DE
                    legalAddress.country: DE
                    bpn: BPNL000000000000
              ServiceOffering:
                description: payload to create ServiceOffering
                value:
                  externalId: ID01234-123-4321
                  type: ServiceOffering
                  holder: BPNL000000000000
                  issuer: CAXSDUMMYCATENAZZ
                  providedBy: https://participant.url
                  aggregationOf: https://aggr1.url, https://aggr2.url
                  termsAndConditions: https://raw.githubusercontent.com/eclipse-tractusx/sd-factory/main/LICENSE
                  policies: policy1, policy2
      responses:
        '202':
          description: request has been accepted for processing
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    SelfDescriptionSchema:
      type: object
      properties:
        type:
          type: string
        holder:
          type: string
        issuer:
          type: string
        externalId:
          type: string
      required:
        - type
        - holder
        - issuer
        - externalId
    RegistrationNumberSchema:
      type: object
      description: Registration Number element
      properties:
        type:
          type: string
          description: the mean to request data retrieval
          enum:
            - taxID
            - vatID
            - EUID
            - EORI
            - leiCode
        value:
          type: string
          description: Registration Number value
          minLength: 1
          maxLength: 128
    LegalPersonSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - type: object
          properties:
            registrationNumber:
              type: array
              uniqueItems: true
              minItems: 1
              maxItems: 512
              description: A list of registration numbers
              items:
                $ref: '#/components/schemas/RegistrationNumberSchema'
            headquarterAddress.country:
              type: string
            legalAddress.country:
              type: string
            bpn:
              type: string
          required:
            - registrationNumber
            - headquarterAddress.country
            - legalAddress.country
            - bpn
    ServiceOfferingSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - type: object
          properties:
            providedBy:
              type: string
              format: uri
            aggregationOf:
              type: string
            termsAndConditions:
              type: string
            policies:
              type: string
          required:
            - providedBy
security:
  - bearerAuth: []
