ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  className: "nginx"
  host: "dummy.dev.demo.catena-x.net"
  hosts:
    - host: dummy.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: ImplementationSpecific


  tls:
    - tlsName: dummy.dev.demo.catena-x.net-tls
      hosts:
        - dummy.dev.demo.catena-x.net

      
# -- Pod resources requests and limits configuration
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 300Mi
